name: 自动同步原仓库
on:
  schedule:
    - cron: '1 5 * * 6'  # 每周一同步，适配原仓库周更节奏
  workflow_dispatch:  # 允许手动触发同步
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
      - name: 同步上游仓库更新
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: hehonghui/awesome-english-ebooks  # 需修改，例：octocat/Spoon-Knife
          upstream_sync_branch: master  # 需修改，填原仓库分支
          target_sync_branch: master  # 需修改，填你Fork仓库的对应分支
